// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2SPzLnm3mvj4vIe80qRVei3XtjWZnd7g',
    appId: '1:492695493840:web:3d14a787c093173a8f92d5',
    messagingSenderId: '492695493840',
    projectId: 'flutter-chat-app-5e822',
    authDomain: 'flutter-chat-app-5e822.firebaseapp.com',
    storageBucket: 'flutter-chat-app-5e822.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYbUYn45EmwBJmzS1dX9Xa5lrjpPHt3js',
    appId: '1:492695493840:android:1a679c7d4556d8a88f92d5',
    messagingSenderId: '492695493840',
    projectId: 'flutter-chat-app-5e822',
    storageBucket: 'flutter-chat-app-5e822.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv8zYHLDCLdi8ZOvztVdqYvfjOd8X8KhY',
    appId: '1:492695493840:ios:ef8d5890b5ba33b48f92d5',
    messagingSenderId: '492695493840',
    projectId: 'flutter-chat-app-5e822',
    storageBucket: 'flutter-chat-app-5e822.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv8zYHLDCLdi8ZOvztVdqYvfjOd8X8KhY',
    appId: '1:492695493840:ios:ef8d5890b5ba33b48f92d5',
    messagingSenderId: '492695493840',
    projectId: 'flutter-chat-app-5e822',
    storageBucket: 'flutter-chat-app-5e822.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2SPzLnm3mvj4vIe80qRVei3XtjWZnd7g',
    appId: '1:492695493840:web:19feffccce29a2738f92d5',
    messagingSenderId: '492695493840',
    projectId: 'flutter-chat-app-5e822',
    authDomain: 'flutter-chat-app-5e822.firebaseapp.com',
    storageBucket: 'flutter-chat-app-5e822.appspot.com',
  );

}